name: lms-haskell-integration
version: 0.1.0
github: "your-username/your-repo"
license: MIT
author: "Your Name"
maintainer: "your.email@example.com"
copyright: "2025 Your Name"

extra-source-files:
  - README.md

description: Haskell integration components for LMS platform

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - vector
  - containers
  - parallel
  - template-haskell

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O2
  - -fllvm

library:
  source-dirs: src
  exposed-modules:
    - Sync.CRDT
    - Blockchain.Verification
    - Query.Optimizer
    - Parser.CompletionRules
    - Parser.QueryLanguage
  build-tools:
    - alex:alex
    - happy:happy

executables:
  lms-haskell-analyzer:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lms-haskell-integration