resolver: lts-20.5

packages:
  - .

extra-deps:
  - vector-0.13.0.0
  - parallel-3.2.2.0
  - alex-3.2.7.1
  - happy-1.20.1.1

flags: {}

extra-package-dbs: []

system-ghc: true

ghc-options:
  "$locals": -fllvm -optlo-O3

build:
  build-tools:
    alex: 3.2.7.1
    happy: 1.20.1.1