[package]
name = "blockchain-wasm"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0" # Latest stable as of April 2025

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Database and ORM
sqlx = { version = "0.8.3", features = ["runtime-tokio", "sqlite", "macros"] }

# Core dependencies for async/await
tokio = { version = "1", features = ["full"], optional = true }
futures = "0.3.30"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Date/Time handling
chrono = "0.4"

# Error handling and async traits
thiserror = "1.0"
anyhow = "1.0.76"
async-trait = "0.1.77"

# Configuration
config = "0.15.11"

# Logging
log = "0.4"
env_logger = "0.11.8"
simple_logger = "4.3"

# CLI utilities
clap = { version = "4.4.11", features = ["derive"] }

# Token encoding for AI
tiktoken-rs = "0.5.8"

# Regular expressions
regex = "1.10.3"

# Frontend - existing Leptos dependencies
leptos = { version = "0.6", features = ["serde", "nightly"] }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_wasi = { version = "0.1.3", optional = true }
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
js-sys = "0.3.66"
serde-wasm-bindgen = "0.6.5"
console_error_panic_hook = "0.1.7"
gloo-net = "0.6.0"

# Authentication and security
base64 = "0.21.5"  # Change from 0.22.1 to match the patched version
jsonwebtoken = "9.3.1"
argon2 = "0.5.2"
rand_core = { version = "0.9.3", features = ["std"] }

# Web framework
axum = { version = "0.7", optional = true }

# Actix web framework
actix-web = { version = "4.0" }
actix-cors = "0.6"

# WebAssembly utilities
web-sys = { version = "0.3" }

# Environment variable management
dotenv = "0.15"

# Path difference utility
pathdiff = "0.2"

# Logging
slog = "2.7"

# Testing
mockall = "0.13.1"

# UUID
uuid = { version = "1.3", features = ["v4", "serde"] }

# WebAssembly dependencies for file_system_utils

# File system traversal
walkdir = "2.3"

[dev-dependencies]
# Testing utilities
mockito = "1.2.0"
tokio-test = "0.4.3"
test-log = "0.2.13"
pretty_assertions = "1.4.0"

[build-dependencies]
# For build script
toml = "0.8.20"
serde = { version = "1.0.193", features = ["derive"] }
tauri-build = { version = "2.1.1", features = [] }

[workspace]
members = [
    "src-tauri",
    "tools/project-analyzer"
]

[workspace.package]
edition = "2021"
authors = ["LMS Team"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hyper = { version = "1.6.0", features = ["full"] }

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:axum",
    "dep:tokio",
    "dep:leptos_axum"
]
wasi = ["leptos/hydrate", "dep:leptos_wasi"]

[package.metadata.wasm]
wasm-bindgen-cli = "0.2"

[package.metadata.leptos]
# Build options - required for both server and client
style-file = "style/output.css"
assets-dir = "assets"
site-root = "target/site"
site-pkg-dir = "pkg"

[lib]
crate-type = ["cdylib"]

[profile.dev]
# Your dev profile settings
