[package]
name = "lms-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.5", features = ["csr"] }
leptos_meta = { version = "0.5", features = ["csr"] }
leptos_router = { version = "0.5", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
js-sys = "0.3.77"
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
console_error_panic_hook = "0.1.7"
gloo-net = "0.5" # For HTTP requests in WASM
base64 = "0.22.1"  # Restore to the latest version

[workspace]
members = ["src-tauri", "shared"]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = ["json"] }

[patch.crates-io]
base64 = { git = "https://github.com/marshallpierce/rust-base64", branch = "master" }
