[package]
name = "lms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Core dependencies for async/await
tokio = { version = "1.28", features = ["full"] }
futures = "0.3"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Date/Time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling and async traits
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"

# Configuration
config = "0.13"

# Logging
log = "0.4"
env_logger = "0.10"

# CLI utilities (if needed)
clap = { version = "4.3", features = ["derive"] }

# Additional dependencies
leptos = { version = "0.5", features = ["csr"] }
leptos_meta = { version = "0.5", features = ["csr"] }
leptos_router = { version = "0.5", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"
js-sys = "0.3.77"
serde-wasm-bindgen = "0.6.5"
console_error_panic_hook = "0.1.7"
gloo-net = "0.5" # For HTTP requests in WASM
base64 = "0.22.1"  # Restore to the latest version

[dev-dependencies]
# Testing utilities
mockito = "1.0"
tokio-test = "0.4"

[workspace]
members = ["src-tauri", "shared"]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hyper = { version = "0.14", features = ["full"] }

[patch.crates-io]
base64 = { git = "https://github.com/marshallpierce/rust-base64", branch = "master" }
