[package]
name = "lms"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0" # Latest stable as of April 2025

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Database and ORM
sea-orm = { version = "0.12.3", features = ["runtime-tokio-native-tls", "macros", "with-chrono", "with-json"] }
sea-orm-migration = "1.1.8"
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio-native-tls"] }

# Core dependencies for async/await
tokio = { version = "1.44.2", features = ["full"] }
futures = "0.3.30"

# HTTP client
reqwest = { version = "0.12.14", features = ["json", "rustls-tls"] }

# Serialization/Deserialization
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

# Date/Time handling
chrono = { version = "0.4.31", features = ["serde"] }

# Error handling and async traits
thiserror = "2.0.12"
anyhow = "1.0.76"
async-trait = "0.1.77"

# Configuration
config = "0.15.9"

# Logging
log = "0.4.20"
env_logger = "0.11.8"

# CLI utilities
clap = { version = "4.4.11", features = ["derive"] }

# Frontend - existing Leptos dependencies
leptos = { version = "0.7.7", features = ["csr"] }
leptos_meta = { version = "0.7.8" }
leptos_router = { version = "0.7.8" }
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
js-sys = "0.3.66"
serde-wasm-bindgen = "0.6.5"
console_error_panic_hook = "0.1.7"
gloo-net = "0.6.0"

# Authentication and security
base64 = "0.22.1"  # Latest stable version
jsonwebtoken = "9.3.1"
argon2 = "0.5.2"
rand_core = { version = "0.9.3", features = ["std"] }

# Web framework
axum = "0.8.3"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["cors", "trace"] }

# Testing
mockall = "0.13.1"

[dev-dependencies]
# Testing utilities
mockito = "1.2.0"
tokio-test = "0.4.3"
test-log = "0.2.13"
pretty_assertions = "1.4.0"

[build-dependencies]
# For build script
toml = "0.8.20"
serde = { version = "1.0.193", features = ["derive"] }

[workspace]
members = ["src-tauri", "shared"]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hyper = { version = "1.6.0", features = ["full"] }

[features]
default = ["sqlite"]
sqlite = []
