# Unified Analyzer Configuration

# General configuration
[general]
project_name = "EduConnect"
output_dir = "docs"
log_level = "info"

# Documentation directories
[output]
docs_dir = "docs"
api_dir = "docs/api"
architecture_dir = "docs/architecture"
models_dir = "docs/models"
integration_dir = "docs/integration"
technical_dir = "docs/technical"
visualizations_dir = "docs/visualizations"
analysis_dir = "docs/analysis"
rag_dir = "docs/rag_knowledge_base"
development_dir = "docs/development"

# Documentation generation options
[documentation]
# Whether to generate high priority documentation
generate_high_priority = true
# Whether to generate medium priority documentation
generate_medium_priority = true
# Whether to generate low priority documentation
generate_low_priority = false
# Whether to generate visualizations
generate_visualizations = true

# High priority documentation
[documentation.high_priority]
central_reference_hub = true
api_documentation = true
implementation_details = true
testing_documentation = true
technical_debt_report = true
summary_report = true

# Medium priority documentation
[documentation.medium_priority]
synchronization_architecture = true
database_architecture = true

# Visualization settings
[visualizations]
api_map = true
component_tree = true
db_schema = true
migration_roadmap = true

# Visualization directories
[visualizations.directories]
api_map_dir = "docs/visualizations/api_map"
component_tree_dir = "docs/visualizations/component_tree"
db_schema_dir = "docs/visualizations/db_schema"
migration_roadmap_dir = "docs/visualizations/migration_roadmap"

# Project information
[project]
name = "Ordo"
description = "Offline-first learning management system with integrated forum"
version = "0.1.0"
repository = "https://github.com/ordokr/LMS.git"

# Source code paths
[paths]
canvas_path = "C:\\Users\\Tim\\Desktop\\port\\canvas"
discourse_path = "C:\\Users\\Tim\\Desktop\\port\\discourse"
lms_path = "C:\\Users\\Tim\\Desktop\\LMS"

# Analysis options
[analysis]
# Analyzers to use
analyzers = ["file_structure", "ruby_rails", "ember", "react", "template", "route", "api", "dependency", "auth_flow", "offline_first_readiness", "database_schema", "business_logic", "canvas", "discourse"]
# Maximum depth to search for files
max_depth = 10
# File extensions to include in analysis
include_extensions = [".rs", ".js", ".ts", ".jsx", ".tsx", ".html", ".css", ".scss", ".md", ".toml", ".json"]
# Directories to exclude from analysis
exclude_dirs = ["node_modules", "target", "dist", "build", ".git"]

# Integration Advisor configuration
[analysis.integration_advisor]
enabled = true
entity_mapping = true
feature_detection = true
code_quality = true
conflict_detection = true
integration_tracking = true
recommendations = true

# Entity Mapping configuration
[analysis.entity_mapping]
similarity_threshold = 0.5
exact_match_bonus = 0.3
field_match_weight = 0.7
name_match_weight = 0.3

# Feature Detection configuration
[analysis.feature_detection]
categories = ["course_mgmt", "assignment_mgmt", "grading", "discussions", "auth", "roles", "moderation", "tagging"]
controller_weight = 0.5
route_weight = 0.3
view_weight = 0.2

# Code Quality configuration
[analysis.code_quality]
usefulness_threshold_high = 80
usefulness_threshold_medium = 50
complexity_weight = 0.4
loc_weight = 0.2
comment_coverage_weight = 0.2
cohesion_weight = 0.2

# Conflict Detection configuration
[analysis.conflict_detection]
naming_conflict_threshold = 0.8
semantic_conflict_threshold = 0.6

# Integration Tracking configuration
[analysis.integration_tracking]
entity_weight = 0.5
feature_weight = 0.5

# Recommendations configuration
[analysis.recommendations]
max_recommendations = 20
high_priority_threshold = 4
medium_priority_threshold = 2

# Performance configuration
[performance]
parallel_processing = true
enable_caching = true
incremental_analysis = true
cache_dir = ".cache"
max_memory_mb = 2048
timeout_seconds = 7200
