# Unified Analyzer Configuration

# Output directories
[output]
docs_dir = "docs"
api_dir = "docs/api"
architecture_dir = "docs/architecture"
models_dir = "docs/models"
integration_dir = "docs/integration"

# Documentation generation options
[documentation]
# Whether to generate high priority documentation
generate_high_priority = true
# Whether to generate medium priority documentation
generate_medium_priority = true
# Whether to exclude AI/Gemini-related content
exclude_ai_content = true

# High priority documentation
[documentation.high_priority]
central_reference_hub = true
api_documentation = true
implementation_details = true
testing_documentation = true
technical_debt_report = true
summary_report = true

# Medium priority documentation
[documentation.medium_priority]
synchronization_architecture = true
database_architecture = true

# Project information
[project]
name = "LMS"
description = "Learning Management System"
version = "0.1.0"
repository = "https://github.com/ordokr/LMS.git"

# Analysis options
[analysis]
# Maximum depth to search for files
max_depth = 10
# File extensions to include in analysis
include_extensions = [".rs", ".js", ".ts", ".jsx", ".tsx", ".html", ".css", ".scss", ".md", ".toml", ".json"]
# Directories to exclude from analysis
exclude_dirs = ["node_modules", "target", "dist", "build", ".git"]
