[package]
name = "index-project"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "index-project"
path = "index_project.rs"

[[bin]]
name = "migration-utility"
path = "migration_utility/src/main.rs"

[dependencies]
chrono = "0.4"