# ... existing CI configuration ...

jobs:
  build:
    # ... existing build job ...
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          
      - name: Install dependencies
        run: |
          cargo install wasm-pack
          cargo install cargo-make
          
      - name: Run backend tests
        run: cargo test --manifest-path src-tauri/Cargo.toml
        
      - name: Run frontend tests
        run: |
          cd frontend
          wasm-pack test --headless --chrome
          
      - name: Run integration tests
        run: cargo make test_integration